adding new changes

diff --git a/.github/workflows/azure-static-web-apps-wonderful-desert-04ea24410.yml b/.github/workflows/azure-static-web-apps-wonderful-desert-04ea24410.yml
--- a/.github/workflows/azure-static-web-apps-wonderful-desert-04ea24410.yml
+++ b/.github/workflows/azure-static-web-apps-wonderful-desert-04ea24410.yml
@@ -24,13 +24,15 @@ jobs:
       - name: Build Frontend
         run: |
           cd frontend
-          npm run build 
+          npm run build  
+          if [ ! -d "dist" ]; then echo "Build failed: dist directory does not exist."; exit 1; fi
       - name: Copy routes.json
         run: |
           cd frontend
           cp routes.json dist/  # Ensure routes.json is copied to the output directory
       - name: Check if routes.json is present
         run: |
+          cd frontend
           ls dist/  # List files in dist to check if routes.json is there
       - name: Deploy to Azure
         id: builddeploy
@@ -44,6 +46,7 @@ jobs:
           output_location: "dist"
         env:
           VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
+
 
 
   close_pull_request_job:
