adding changes

diff --git a/.github/workflows/azure-static-web-apps-mango-forest-09f2f4f03.yml b/.github/workflows/azure-static-web-apps-mango-forest-09f2f4f03.yml
--- a/.github/workflows/azure-static-web-apps-mango-forest-09f2f4f03.yml
+++ b/.github/workflows/azure-static-web-apps-mango-forest-09f2f4f03.yml
@@ -11,15 +11,40 @@ on:
 
 jobs:
   build_and_deploy_job:
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
     runs-on: ubuntu-latest
-    name: Build and Deploy Job
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
           lfs: false
-      - name: Build And Deploy
+      
+      - name: Install Dependencies
+        run: |
+          cd frontend
+          npm install
+      
+      - name: Build Frontend
+        run: |
+          cd frontend
+          npm run build  
+          if [ ! -d "dist" ]; then echo "Build failed: dist directory does not exist."; exit 1; fi
+      
+      - name: Copy staticwebapp.config.json
+        run: |
+          cd frontend
+          cp staticwebapp.config.json dist/  # Ensure staticwebapp.config.json is copied to the output directory
+
+      - name: Check if staticwebapp.config.json is present
+        run: |
+          cd frontend
+          ls dist/  # List files in dist to check if staticwebapp.config.json is there
+          
+      - name: Check staticwebapp.config.json content
+        run: |
+          cd frontend
+          cat dist/staticwebapp.config.json  # Print the contents to the logs
+
+      - name: Deploy to Azure
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
         with:
@@ -29,9 +54,10 @@ jobs:
           ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
           # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
           app_location: "./frontend" # App source code path
-          api_location: "" # Api source code path - optional
-          output_location: "build" # Built app content directory - optional
-          ###### End of Repository/Build Configurations ######
+          api_location: "./api" # Api source code path - optional
+          output_location: "dist" # Built app content directory - optional
+        env:
+            VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
